# Preprocesamiento de datos

In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#importamos el dataset
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values


In [4]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [5]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


### Tratamiento de datos faltantes

In [6]:
#Cuando tenemos datos faltantes y estos no representan un gran porcentaje de los datos podemos simplemente eliminarlos
#pero hay ocasiones en las que es mejor remplazarlos por la media de los datos
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


### Codificamos los datos categoricos

 Codificando la variable dependiente

In [7]:
#Cuando tenemos categorias en los datos es necesario codificarlas para que el algoritmo pueda entenderlas
#y lo hacemos pasando los datos a numeros

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Codificando la variable dependiente

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

print(Y)


[0 1 0 0 1 1 0 1 0 1]


### Partiendo los datasets en el set de entrenamiento y el set de prueba

In [10]:
#Dividimos el dataset en conjunto de entrenamiento y conjunto de testing para que el algoritmo pueda aprender
#y no memorice los datos y asi poder predecir nuevos datos que no conoce y asi saber si el algoritmo esta bien
#o no y no sobreajustar los datos
from sklearn.model_selection import train_test_split
#Se divide en 4 partes, 2 para entrenamiento y 2 para testing una de entrenamiento y una de testing para las variables independientes 
#y otras para las variables dependientes
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)



In [11]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [12]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [13]:
print(Y_train)

[0 1 0 0 1 1 0 1]


In [14]:
print(Y_test)

[0 1]


### Escalado de caracteristicas

In [15]:
#Las variables se deben escalar para que no haya variables que dominen a las demas y asi el algoritmo no se centre en ellas
from sklearn.preprocessing import StandardScaler
#StandardScaler es para escalar las variables independientes
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
#Solo se hace transform en el conjunto de testing porque ya se ha hecho fit en el conjunto de entrenamiento 
#y no tendría sentido hacer fit en el conjunto de testing 
X_test[:, 3:] = sc.transform(X_test[:, 3:])
#No se escala la variable dependiente porque es una variable categorica y no numerica y no se puede escalar una variable categorica


In [16]:
#Ahora todos los valores se encuentran entre -3 y 3
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [17]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
